# -*- coding: utf-8 -*-
"""Copy of Untitled65.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lGiet7D1Ey5hmi-dicazvfl0NU8lO4Vf
"""

str1="Anil Kumar" 
print(str1)
print(str1.rstrip())