# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOQHZEhjDhng1OVVVtwjkqu7LpQOYifU
"""

str1 = 'The GITAM University .'
print()
print(str1.count("GITAM "))
print()