# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOQHZEhjDhng1OVVVtwjkqu7LpQOYifU
"""

def Convert(string): 
 
    list1= list(string.split(" ")) 
 
    return list1
str1 = "The GITAM University "
 
print(Convert(str1))