# -*- coding: utf-8 -*-
"""Copy of Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WOQHZEhjDhng1OVVVtwjkqu7LpQOYifU
"""

s= "refrigerator" 
count = 0 
for i in s:
   count = count+1 
print (count)

